website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Property, Tenant, Payment
from . import db
import json
from sqlalchemy import *
views = Blueprint('views', __name__)
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, Length
import datetime

class PropertyForm(FlaskForm):
    address = StringField('Address', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    state = StringField('State', validators=[DataRequired(), Length(min=2, max=2)])
    zip_code = StringField('Zip Code', validators=[DataRequired()])
    bedrooms = IntegerField('Bedrooms') # Add other fields as needed
    bathrooms = IntegerField('Bathrooms')
    square_footage = IntegerField('Square Footage')
    status = StringField('Status')
    submit = SubmitField('Update Property') 

class AddPropertyForm(FlaskForm):
    address = StringField('Address', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    state = StringField('State', validators=[DataRequired(), Length(min=2, max=2)])
    zip_code = StringField('Zip Code', validators=[DataRequired()])
    bedrooms = IntegerField('Bedrooms') 
    bathrooms = IntegerField('Bathrooms')
    square_footage = IntegerField('Square Footage')
    status = StringField('Status')
    submit = SubmitField('Add Property')

class AddTenantForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired()])
    phone_number = StringField('Phone Number', validators=[DataRequired()])
    lease_start_date = StringField('Lease Start Date', validators=[DataRequired()])
    lease_end_date = StringField('Lease End Date', validators=[DataRequired()])
    monthly_rent = IntegerField('Monthly Rent', validators=[DataRequired()])
    security_deposit = IntegerField('Security Deposit', validators=[DataRequired()])
    submit = SubmitField('Add Tenant')

class AddPaymentForm(FlaskForm):
    date = StringField('Date', validators=[DataRequired()])
    amount = IntegerField('Amount', validators=[DataRequired()])
    payment_type = StringField('Payment Type', validators=[DataRequired()])
    submit = SubmitField('Add Payment')

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    status_filter = request.args.get('status_filter')  # Get filter value
    #db.session.execute(text('INSERT INTO tenant (first_name, last_name, email, phone_number, lease_start_date, lease_end_date, monthly_rent, security_deposit, property_id) VALUES ("John", "Doe", "jahn@doe.com", "1234567890", "2021-01-01", "2021-12-31", 1000, 1000, 1)'))
    #properties_query = select(Property).where(Property.owner_id == current_user.id)
    properties_query = text("""
            SELECT * 
            FROM property 
            LEFT OUTER JOIN tenant
            ON property.property_id=tenant.property_id
            WHERE owner_id = :owner_id
        """)
    avg_rent_query = text("""
            SELECT ROUND(AVG(monthly_rent), 2)
            FROM tenant
            WHERE property_id IN (SELECT
            property_id
            FROM property
            WHERE owner_id = :owner_id)
        """)
    avg_sqft_query = text("""
            SELECT ROUND(AVG(square_footage), 2)
            FROM property
            WHERE owner_id = :owner_id
        """)
    payment_query = text("""
            SELECT property_id, amount, date, payment_type
            FROM payment
            WHERE property_id IN (SELECT
            property_id
            FROM property
            WHERE owner_id = :owner_id)
        """)
    if status_filter == 'Vacant':
        #properties_query = select(Property).where(and_(Property.status == 'Vacant', Property.owner_id == current_user.id))
        properties_query = text("""
            SELECT * 
            FROM property 
            LEFT OUTER JOIN tenant
            ON property.property_id=tenant.property_id
            WHERE owner_id = :owner_id
            AND status = "Vacant"
        """)
        avg_rent_query = text("""
            SELECT ROUND(AVG(monthly_rent), 2)
            FROM tenant
            WHERE property_id IN (SELECT
            property_id
            FROM property
            WHERE owner_id = :owner_id
            AND status = "Vacant")
        """)
        avg_sqft_query = text("""
                SELECT ROUND(AVG(square_footage), 2)
                FROM property
                WHERE owner_id = :owner_id
                AND status = "Vacant"
            """)
        payment_query = text("""
            SELECT property_id, amount, date, payment_type
            FROM payment
            WHERE property_id IN (SELECT
            property_id
            FROM property
            WHERE owner_id = :owner_id)
        """)

    elif status_filter == 'Occupied':
        #properties_query = select(Property).where(and_(Property.status == 'Occupied', Property.owner_id == current_user.id))
        properties_query = text("""
            SELECT * 
            FROM property 
            LEFT OUTER JOIN tenant
            ON property.property_id=tenant.property_id
            WHERE owner_id = :owner_id
            AND status = "Occupied"
        """)
        avg_rent_query = text("""
            SELECT ROUND(AVG(monthly_rent), 2)
            FROM tenant
            WHERE property_id IN (SELECT
            property_id
            FROM property
            WHERE owner_id = :owner_id
            AND status = "Occupied")
        """)
        avg_sqft_query = text("""
                SELECT ROUND(AVG(square_footage), 2)
                FROM property
                WHERE owner_id = :owner_id
                AND status = "Occupied"
            """)
        payment_query = text("""
            SELECT property_id, amount, date, payment_type
            FROM payment
            WHERE property_id IN (SELECT
            property_id
            FROM property
            WHERE owner_id = :owner_id)
        """)
        
    
    payments = db.session.execute(payment_query, {'owner_id': current_user.id})    
    result = db.session.execute(properties_query, {'owner_id': current_user.id})
    avg_rent = db.session.execute(avg_rent_query, {'owner_id': current_user.id})
    avg_sqft = db.session.execute(avg_sqft_query, {'owner_id': current_user.id})
    status = db.session.execute(text('SELECT DISTINCT status FROM property WHERE owner_id = :owner_id'), {'owner_id': current_user.id})

    return render_template('home.html', properties=result, status=status, avg_rent=avg_rent, avg_sqft=avg_sqft, payments=list(payments)) #current_user.properties

@views.route('/property/add', methods=['GET', 'POST'])
@login_required
def add_property():
    form = AddPropertyForm()
    if form.validate_on_submit():
        new_property = Property(
            address=form.address.data,
            city=form.city.data,
            state=form.state.data,
            zip_code=form.zip_code.data,
            bedrooms=form.bedrooms.data,
            bathrooms=form.bathrooms.data,
            square_footage=form.square_footage.data,
            status=form.status.data,
            owner_id=current_user.id
        )
        db.session.add(new_property)
        db.session.commit()
        flash('Property added successfully!', 'success')
        if new_property.status == 'Vacant':
            return redirect(url_for('views.home'))
        else:
            return redirect(url_for('views.add_tenant', property_id=new_property.property_id)) 
    return render_template('add.html', form=form)

@views.route('/<int:property_id>/add_tenant', methods=['GET', 'POST'])
@login_required
def add_tenant(property_id):
    form = AddTenantForm()
    if form.validate_on_submit():
        new_tenant = Tenant(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            phone_number=form.phone_number.data,
            lease_start_date=datetime.datetime.strptime(form.lease_start_date.data, '%m/%d/%Y').date(),
            lease_end_date=datetime.datetime.strptime(form.lease_end_date.data, '%m/%d/%Y').date(),
            monthly_rent=form.monthly_rent.data,
            security_deposit=form.security_deposit.data,
            property_id=property_id
        )
        db.session.add(new_tenant)
        db.session.commit()
        flash('Tenant added successfully!', 'success')
        return redirect(url_for('views.home')) 
    return render_template('add_tenant.html', form=form)

@views.route('/<int:property_id>/<int:tenant_id>/add_payment', methods=['GET', 'POST'])
@login_required
def add_payment(property_id, tenant_id):
    form = AddPaymentForm()
    if form.validate_on_submit():
        new_payment = Payment(
            date=datetime.datetime.strptime(form.date.data, '%m/%d/%Y').date(),
            amount=form.amount.data,
            payment_type=form.payment_type.data,
            property_id=property_id,
            tenant_id=tenant_id
        )
        db.session.add(new_payment)
        db.session.commit()
        flash('Payment added successfully!', 'success')
        return redirect(url_for('views.home')) 
    return render_template('add_payment.html', form=form)

@views.route('/delete-property', methods=['POST'])
def delete_property():  
    prop = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    print(prop)
    propId = prop['propId']
    prop = Property.query.get(propId)
    if prop:
        if prop.owner_id == current_user.id:
            db.session.delete(prop)
            db.session.commit()

    return jsonify({})

@views.route("/property/<int:property_id>/edit'", methods=['GET', 'POST'])
def edit_property(property_id):

website/templates/add.html
{% extends "base.html" %}
{% block title %}Add Property{% endblock %}

{% block content %}

<div class="container">
<br />
  <h1 align="center">Add Property</h1>
  <br />
  <form method="POST">
    {{ form.hidden_tag() }} 

    {{ form.address.label(class="form-label") }}
    {{ form.address(class="form-control") }} 
    {% for error in form.address.errors %}
      <span style="color: red;">{{ error }}</span>
    {% endfor %} <br>

    {{ form.city.label(class="form-label") }}
    {{ form.city(class="form-control") }}<br>

    {{ form.state.label(class="form-label") }}
    {{ form.state(class="form-control") }}<br>

    {{ form.zip_code.label(class="form-label") }}
    {{ form.zip_code(class="form-control") }}<br>

    {{ form.bedrooms.label(class="form-label") }}
    {{ form.bedrooms(class="form-control") }}<br>

    {{ form.bathrooms.label(class="form-label") }}
    {{ form.bathrooms(class="form-control") }}<br>

    {{ form.square_footage.label(class="form-label") }}
    {{ form.square_footage(class="form-control") }}<br>

  
    <select name="status" class="form-select">
      <option value="Vacant">Vacant</option>
      <option value="Occupied">Occupied</option>
    </select> 
    
    <br>
    <br>

    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>
{% endblock %}

website/templates/add_payment.html
{%extends "base.html"%} {% block title %}Add Payment{% endblock %} {% block content %}
<div class="container">
    <br />
    <h1 align="center">Add Payment</h1>
    <br />
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.amount.label(class="form-label") }}
        {{ form.amount(class="form-control") }}

        {% for error in form.amount.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %} <br>

        {{ form.date.label(class="form-label") }}
        {{ form.date(class="form-control") }}<br>

        {{ form.payment_type.label(class="form-label") }}
        {{ form.payment_type(class="form-control") }}<br>

        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

website/templates/add_tenant.html
{% extends "base.html" %} {% block title %}Add Tenant{% endblock %} {% block content %}

<div class="container">
    <br />
    <h1 align="center">Add Tenant</h1>
    <br />
    <form method="POST">
        {{ form.hidden_tag() }}
    
        {{ form.first_name.label(class="form-label") }}
        {{ form.first_name(class="form-control") }}
        {% for error in form.first_name.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %} <br>
    
        {{ form.last_name.label(class="form-label") }}
        {{ form.last_name(class="form-control") }}<br>
    
        {{ form.email.label(class="form-label") }}
        {{ form.email(class="form-control") }}<br>
    
        {{ form.phone_number.label(class="form-label") }}
        {{ form.phone_number(class="form-control") }}<br>

        {{ form.monthly_rent.label(class="form-label") }}
        {{ form.monthly_rent(class="form-control") }}<br>

        {{ form.lease_start_date.label(class="form-label") }}
        {{ form.lease_start_date(class="form-control") }}<br>
    
        {{ form.lease_end_date.label(class="form-label") }}
        {{ form.lease_end_date(class="form-control") }}<br>

        {{ form.security_deposit.label(class="form-label") }}
        {{ form.security_deposit(class="form-control") }}<br>
    
        {{ form.submit(class="btn btn-primary") }}

    </form>
    
</div>
    
    {% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1">Rentrack</span>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
function deleteProperty(propId) {
  fetch("/delete-property", {
    method: "POST",
    body: JSON.stringify({ propId: propId }),
  }).then((_res) => {
    window.location.href = "/";
  });
}
</script>
{% endblock %}
  </body>
  <script>
    $('#proplist a').on('click', function (e) {
e.preventDefault()
$(this).tab('show')
})
  </script>
</html>

website/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit Property{% endblock %}

{% block content %}
<div class="container">
    <br />
  <h1 align="center">Edit Property</h1>
    <br />
  <form method="POST">
    {{ form.hidden_tag() }} {{ form.address.label(class="form-label") }}
    {{ form.address(class="form-control") }} 
    {% for error in form.address.errors %}
      <span style="color: red;">{{ error }}</span>
    {% endfor %} <br>

    {{ form.city.label(class="form-label") }}
    {{ form.city(class="form-control") }}<br>

    {{ form.state.label(class="form-label") }}
    {{ form.state(class="form-control") }}<br>

    {{ form.zip_code.label(class="form-label") }}
    {{ form.zip_code(class="form-control") }}<br>

    {{ form.bedrooms.label(class="form-label") }}
    {{ form.bedrooms(class="form-control") }}<br>

    {{ form.bathrooms.label(class="form-label") }}
    {{ form.bathrooms(class="form-control") }}<br>

    {{ form.square_footage.label(class="form-label") }}
    {{ form.square_footage(class="form-control") }}<br>

    <select name="status" class="form-select">
      <option value="Vacant">Vacant</option>
      <option value="Occupied">Occupied</option>
    </select> 

    <br>
    <br>

    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}

<br />
<h1 align="center">🏘️Properties</h1>
<br />
<div class="container"> 
  <form method="GET">
    <select name="status_filter" class="form-select">
      <option value="" selected>All Properties</option>
      {% for s in status %}
        <option value="{{ s[0] }}">{{ s[0] }}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary">Filter</button> 
  </form>
  </div>
</div> 
<br />
<div class="container">
  {% for i in avg_rent %}
  Average Monthly Rent: ${{ i[0] }}
  {% endfor %}
  <br />
  {% for j in avg_sqft %}
  Average Square Footage: {{ j[0] }}
  {% endfor %}
  
</div>
<br />
<div class="container"> 
  <div class="row"> 
    {% for property in properties %}
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-header">
            <ul class="nav nav-pills card-header-pills nav-justified" id="proplist" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" href="#property-{{property[0]}}" role="tab" aria-controls="property" aria-selected="true">Property</a>
              </li>
              {% if property[8] == "Occupied" %}
                <li class="nav-item">
                  <a class="nav-link" href="#tenant-info-{{property[0]}}" role="tab" aria-controls="tenant-info" aria-selected="false">Tenant</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#payment-status-{{property[0]}}" role="tab" aria-controls="payment-status" aria-selected="false">Payment</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Tenant</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Payment</a>
                </li>
              {% endif %}
            </ul>
          </div>

          <div class="card-body">
            <h5 class="card-title">{{ property[1] }}</h5>
            <h6 class="card-subtitle mb-2">
              {{ property[2] }}, {{ property[3] }} {{ property[4] }}
            </h6>

            <div class="tab-content mt-3">

              <div class="tab-pane active" id="property-{{property[0]}}" role="tabpanel">
                <p class="card-text">
                  Bedrooms: {{ property[5] }} <br/> 
                  Bathrooms: {{ property[6] }} <br/>
                  Sq. Footage: {{ property[7] }} 
                </p>
                <p class="card-text">Status: {{ property[8] }}</p> 
                <button type="button" class="btn btn-danger" onClick="deleteProperty({{ property[0] }})"> 
                  Delete
                </button> 
                <a href="{{ url_for('views.edit_property', property_id = property[0]) }}" class="btn btn-primary">Edit</a> 
                
                </div>

              <div class="tab-pane" id="tenant-info-{{property[0]}}" role="tabpanel"  aria-labelledby="tenant-info">
                <!--<h5 id="tenant-info">Tenant Info</h5>-->
                <p class="card-text">
                  Name: {{ property[11] }} <br/>
                  Email: {{ property[13] }} <br/>
                  Phone: {{ property[14] }} <br/>
                  Lease Start: {{ property[15] }} <br/>
                  Lease End: {{ property[16] }} <br/>
                  Monthly rent: ${{ property[17] }} <br/>
                  Security Deposit: ${{ property[18] }} <br/>
                </p>
                <!-- <a href="{{ url_for('views.add_tenant', property_id=property[0]) }}" class="btn btn-primary">Add Tenant</a> -->
                <a href="{{ url_for('views.edit_property', property_id = property[0]) }}" class="btn btn-primary">Edit</a> 

                </div>

              <div class="tab-pane" id="payment-status-{{property[0]}}" role="tabpanel"  aria-labelledby="payement-status">
                <!--<h5 id="payment-status">Payment Status</h5>-->
                {% for p in payments %}
                  {% if p[0] == property[0] %}
                    <p class="card-text">
                      Amount: ${{ p[1] }} <br/>
                      Date: {{ p[2] }} <br/>
                      Type: {{ p[3] }} <br/>
                    </p>
                  {% endif %}
                {% endfor %}

                
                <!-- <p class="card-text">
                  Amount: ${{ property[24] }} <br/>
                  Date: {{ property[23] }} <br/>
                  Type: {{ property[25] }} <br/>
                </p> -->
                <a href="{{ url_for('views.add_payment', property_id=property[0], tenant_id = property[10] or 0) }}" class="btn btn-primary">Add Payment</a>
                
              </div>

            </div>
            
          </div>
        </div>
      </div> 
    {% endfor %}
  </div>
</div>

<br />
<div align="center">
  <!--<button type="submit" class="btn btn-primary">Add Property</button>-->
  <a href="{{ url_for('views.add_property') }}" class="btn btn-primary">Add Property</a>
</div>
<br>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <br />
  <h3 align="center">Login</h3>
  <br />
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <br />
  <h3 align="center">Sign Up</h3>
  <br />
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}